### ISSUE TITLE
I have a pydantic error..

### ISSUE THREAD

**Issue by chloamme** [sambanova/toolbench#2]
I successfully set it up based on your instructions. However, I'm getting an error when I run test.py.

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    from action_generator import RagGenerator
  File "/home/azureuser/toolbench/action_generator/__init__.py", line 18, in <module>
    from .rag_generator import RagGenerator
  File "/home/azureuser/toolbench/action_generator/rag_generator.py", line 19, in <module>
    from action_generator.components.retriever import (
  File "/home/azureuser/toolbench/action_generator/components/retriever.py", line 19, in <
  File "/home/azureuser/toolbench/action_generator/components/retriever.py", line 19, in <module>
    from haystack.document_stores import InMemoryDocumentStore, FAISSDocumentStore
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/haystack/__init__.py", 
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/haystack/__init__.py", line 20, in <module>
    from haystack.schema import Document, Answer, Label, MultiLabel, Span, EvaluationResul
    from haystack.schema import Document, Answer, Label, MultiLabel, Span, EvaluationResult
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/haystack/schema.py", li
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/haystack/schema.py", line 44, in <module>
    class Document:
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/dataclasses.py
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/dataclasses.py", line 213, in dataclass
    return create_dataclass(_cls)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/dataclasses.py
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/dataclasses.py", line 204, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_dat
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_dataclasses.py", line 152, in complete_dataclass
    schema = gen_schema.generate_schema(cls, from_dunder_get_core_schema=False)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    schema = self._generate_schema(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 785, in match_type
    return self._dataclass_schema(obj, None)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1348, in _dataclass_schema
    args = sorted(
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1349, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 887, in _generate_dc_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 923, in _common_field_schema
    schema = self._apply_annotations(
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1592, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_sch
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1573, in inner_handler
    schema = self._generate_schema(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 794, in match_type
    return self._match_generic_type(obj, origin)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 818, in _match_generic_type
    return self._union_schema(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1006, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    schema = self._generate_schema(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 798, in match_type
    return self._unknown_type_schema(obj)
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_gen
  File "/home/azureuser/toolbench/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'pandas.core.frame.DataFrame'>. Set `arbitrary_types_allowed=True` in the model_co
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'pandas.core.frame.DataFrame'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to full
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'pandas.core.frame.DataFrame'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__
If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call
If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
For further information visit https://errors.pydantic.dev/2.4/u/schema-for-unknown-type
```

The installed library version is:
pydantic==2.4.2
pydantic_core==2.10.1
farm-haystack==1.15.1

**Comment by yjyj23** [comment]
@chloamme 
Did you solve it?
